# Generated by Django 4.2.6 on 2023-10-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internetOfThings', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTypeParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(choices=[('int', 'integer'), ('float', 'float'), ('string', 'string')])),
                ('deviceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internetOfThings.devicetype')),
            ],
        ),
    ]
