# Generated by Django 4.2.6 on 2023-10-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetOfThings', '0004_devicetypeparam_remove_devicetypeparams_devicetype_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='devicetypeparam',
            constraint=models.UniqueConstraint(fields=('name', 'typeName'), name='UN_DeviceTypeParam_typeName_name'),
        ),
    ]
