# Generated by Django 4.2.5 on 2023-11-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internetOfThings', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='internetOfThings.user'),
            preserve_default=False,
        ),
    ]
