# Generated by Django 4.2.5 on 2023-11-21 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internetOfThings', '0008_system_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('undefined', 'Undefined')], default='undefined', max_length=10),
        ),
        migrations.AlterField(
            model_name='system',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='system',
            unique_together={('system_name', 'owner')},
        ),
        migrations.CreateModel(
            name='Sharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('waiting', 'Waiting'), ('accepted', 'Accepted'), ('declined', 'Declined')], max_length=10)),
                ('share_type', models.CharField(choices=[('user_to_system', 'User to System'), ('owner_to_user', 'Owner to User')], max_length=20)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internetOfThings.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internetOfThings.user')),
            ],
            options={
                'unique_together': {('user', 'system', 'share_type')},
            },
        ),
    ]
