# Generated by Django 4.2.5 on 2023-11-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internetOfThings', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='state',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='waiting', max_length=10),
        ),
    ]
