# Generated by Django 4.2.5 on 2023-11-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internetOfThings', '0011_alter_sharing_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internetOfThings.device')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internetOfThings.system')),
            ],
        ),
        migrations.AddConstraint(
            model_name='systemdevice',
            constraint=models.UniqueConstraint(fields=('device', 'system'), name='UN_SystemDevice_device_system'),
        ),
    ]
