# Generated by Django 4.2.5 on 2023-11-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internetOfThings', '0012_systemdevice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(default='', max_length=1000)),
                ('value', models.IntegerField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='internetOfThings.system')),
            ],
            options={
                'unique_together': {('name', 'system')},
            },
        ),
        migrations.RemoveField(
            model_name='deviceparamvalue',
            name='device',
        ),
        migrations.RemoveField(
            model_name='deviceparamvalue',
            name='param',
        ),
        migrations.RemoveField(
            model_name='devicetypeparam',
            name='deviceType',
        ),
        migrations.RemoveField(
            model_name='systemdevice',
            name='device',
        ),
        migrations.RemoveField(
            model_name='systemdevice',
            name='system',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DeviceParamValue',
        ),
        migrations.DeleteModel(
            name='DeviceType',
        ),
        migrations.DeleteModel(
            name='DeviceTypeParam',
        ),
        migrations.DeleteModel(
            name='SystemDevice',
        ),
    ]
